In [48]:
pip install -i https://mirror-pypi.runflare.com/simple scikit-learn

Looking in indexes: https://mirror-pypi.runflare.com/simple
Collecting scikit-learn
  Downloading https://mirror-pypi.runflare.com/packages/36/4d/4a67f30778a45d542bbea5db2dbfa1e9e100bf9ba64aefe34215ba9f11f6/scikit_learn-1.8.0-cp311-cp311-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (11 kB)
Requirement already satisfied: numpy>=1.24.1 in /home/mohammadjavad/anaconda3/envs/gnn_env/lib/python3.11/site-packages (from scikit-learn) (2.4.2)
Requirement already satisfied: scipy>=1.10.0 in /home/mohammadjavad/anaconda3/envs/gnn_env/lib/python3.11/site-packages (from scikit-learn) (1.17.0)
Collecting joblib>=1.3.0 (from scikit-learn)
  Downloading https://mirror-pypi.runflare.com/packages/7b/91/984aca2ec129e2757d1e4e3c81c3fcda9d0f85b74670a094cc443d9ee949/joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
Collecting threadpoolctl>=3.2.0 (from scikit-learn)
  Downloading https://mirror-pypi.runflare.com/packages/32/d5/f9a850d79b0851d1d4ef6456097579a9005b31fea68726a4ae5f2d82ddd9/threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Downloading https://mirror-pypi.runflare.com/packages/36/4d/4a67f30778a45d542bbea5db2dbfa1e9e100bf9ba64aefe34215ba9f11f6/scikit_learn-1.8.0-cp311-cp311-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (9.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.1/9.1 MB 1.3 MB/s  0:00:07 eta 0:00:01
Downloading https://mirror-pypi.runflare.com/packages/7b/91/984aca2ec129e2757d1e4e3c81c3fcda9d0f85b74670a094cc443d9ee949/joblib-1.5.3-py3-none-any.whl (309 kB)
Downloading https://mirror-pypi.runflare.com/packages/32/d5/f9a850d79b0851d1d4ef6456097579a9005b31fea68726a4ae5f2d82ddd9/threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
Installing collected packages: threadpoolctl, joblib, scikit-learn
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3/3 [scikit-learn][0m [scikit-learn]
Successfully installed joblib-1.5.3 scikit-learn-1.8.0 threadpoolctl-3.6.0
Note: you may need to restart the kernel to use updated packages.

In [41]:
import tensorflow as tf
from tensorflow import keras
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler, LabelBinarizer

from keras.models import Sequential
from keras.layers import Dense, Input
from keras.losses import MeanAbsolutePercentageError
from keras.optimizers import Adam

In [2]:
txt_data_path = "https://raw.githubusercontent.com/emanhamed/Houses-dataset/master/Houses%20Dataset/HousesInfo.txt"

culomns_name = ["bedrooms", "bathrooms", "area", "zipcode", "price"]
df = pd.read_csv(txt_data_path, sep=" ", header=None, names=culomns_name)
df.head(10)

   bedrooms  bathrooms  area  zipcode    price
0         4        4.0  4053    85255   869500
1         4        3.0  3343    36372   865200
2         3        4.0  3923    85266   889000
3         5        5.0  4022    85262   910000
4         3        4.0  4116    85266   971226
5         4        5.0  4581    85266  1249000
6         3        4.0  2544    85262   799000
7         4        5.0  5524    85266  1698000
8         3        4.0  4229    85255  1749000
9         4        5.0  3550    85262  1500000

In [3]:
df.tail(10)

     bedrooms  bathrooms  area  zipcode   price
525         5        3.0  3679    94531  525000
526         4        2.5  1794    94531  380000
527         4        3.5  3420    94531  550000
528         4        3.0  2506    94531  449950
529         4        2.5  2236    94531  495000
530         5        2.0  2066    94531  399900
531         4        3.5  9536    94531  460000
532         3        2.0  2014    94531  407000
533         4        3.0  2312    94531  419000
534         5        3.0  3796    94531  615000

In [4]:
counts = df["zipcode"].value_counts()
type(counts)
unique_zipcodes = counts.index.to_numpy()
counts_zipcodes = counts.values

print(counts_zipcodes.shape)

(49,)

In [5]:
for zipcode, count in zip(unique_zipcodes, counts_zipcodes):
    if count >= 10:
        print(f"{zipcode} --> {count}")

92276 --> 100
93510 --> 60
93446 --> 54
92880 --> 49
94501 --> 41
91901 --> 32
92677 --> 26
94531 --> 22
85255 --> 12
96019 --> 12
85266 --> 11
81524 --> 11
92021 --> 11
93111 --> 11
95220 --> 10

In [6]:
list_least_zipcode = counts[counts.values < 25].index.to_list()

for zipcode in list_least_zipcode:
    idxs = df[df['zipcode'] == zipcode].index
    df.drop(idxs, inplace=True)

In [7]:
df

     bedrooms  bathrooms  area  zipcode    price
30          5        3.0  2520    93446   789000
32          3        2.0  1802    93446   365000
39          3        3.0  2146    93446   455000
80          4        2.5  2464    91901   599000
81          2        2.0  1845    91901   529800
..        ...        ...   ...      ...      ...
499         4        4.0  3000    93446  1495000
500         3        2.0  2330    93446   599900
501         3        2.5  1339    93446   344900
502         3        2.0  1472    93446   309995
503         4        4.0  2681    93446   572000

[362 rows x 5 columns]

In [8]:
df["zipcode"].value_counts()

zipcode
92276    100
93510     60
93446     54
92880     49
94501     41
91901     32
92677     26
Name: count, dtype: int64

In [9]:
train, val = train_test_split(df, test_size=0.2, random_state=42)

In [11]:
train.shape

(289, 5)

In [12]:
val.shape

(73, 5)

In [ ]:
# Normalaize Y based train data
MaxTrain = train["price"].max()

y_train = train["price"] / MaxTrain
y_val = val["price"] / MaxTrain

In [19]:
sc = MinMaxScaler()

In [29]:
train_data_continues = sc.fit_transform(train[['bedrooms', 'bathrooms', 'area']])
val_data_continues = sc.fit_transform(val[['bedrooms', 'bathrooms', 'area']])

In [28]:
binarizer = LabelBinarizer().fit(df['zipcode'])
train_data_categorical = binarizer.transform(train['zipcode'])
val_data_categorical = binarizer.transform(val['zipcode'])

train_data_categorical.shape

(289, 7)

In [31]:
train_data = np.hstack((train_data_continues, train_data_categorical))
val_data = np.hstack((val_data_continues, val_data_categorical))

print(f"Number of features id train data is: {train_data.shape[1]}")
print(f"Number of features id val data is: {val_data.shape[1]}")

Number of features id train data is: 10
Number of features id val data is: 10

In [53]:
model = Sequential()

model.add(Input(shape=(train_data.shape[1], )))
model.add(Dense(8, activation='relu'))
model.add(Dense(4, activation='relu'))
model.add(Dense(1, activation='linear'))

In [54]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_3 (Dense)                 │ (None, 8)              │            88 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 4)              │            36 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 1)              │             5 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 129 (516.00 B)

 Trainable params: 129 (516.00 B)

 Non-trainable params: 0 (0.00 B)

In [55]:
model.compile(optimizer=Adam(learning_rate=0.001, weight_decay=1e-4),
              loss=MeanAbsolutePercentageError())

In [56]:
model.fit(train_data, y_train, validation_data=(val_data, y_val), batch_size=8, epochs=200)

Epoch 1/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 886.4706 - val_loss: 509.6492
Epoch 2/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 345.3121 - val_loss: 143.0024
Epoch 3/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 58.6489 - val_loss: 98.5115
Epoch 4/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 42.0246 - val_loss: 83.5414
Epoch 5/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 41.7203 - val_loss: 90.4052
Epoch 6/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 40.3338 - val_loss: 79.4443
Epoch 7/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 37.5115 - val_loss: 79.3554
Epoch 8/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 37.6460 - val_loss: 82.7304
Epoch 9/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 36.1643 - val_loss: 79.2864
Epoch 10/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 35.7788 - val_loss: 77.3476
Epoch 11/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 36.1298 - val_loss: 74.1900
Epoch 12/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 34.2179 - val_loss: 75.6372
Epoch 13/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 34.6356 - val_loss: 69.3654
Epoch 14/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 35.0623 - val_loss: 68.3531
Epoch 15/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 36.3980 - val_loss: 70.4584
Epoch 16/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 36.3494 - val_loss: 56.3316
Epoch 17/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 35.3476 - val_loss: 65.2057
Epoch 18/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 35.1911 - val_loss: 63.2377
Epoch 19/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 32.5139 - val_loss: 62.9180
Epoch 20/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 31.8667 - val_loss: 64.9359
Epoch 21/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 33.0123 - val_loss: 58.4435
Epoch 22/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 34.5289 - val_loss: 64.6580
Epoch 23/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 31.7702 - val_loss: 64.4279
Epoch 24/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 32.9986 - val_loss: 60.6177
Epoch 25/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 32.1377 - val_loss: 55.7511
Epoch 26/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 31.7762 - val_loss: 55.0432
Epoch 27/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 32.6173 - val_loss: 56.9965
Epoch 28/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 30.0907 - val_loss: 53.2784
Epoch 29/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 31.5093 - val_loss: 57.4658
Epoch 30/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 29.6131 - val_loss: 57.5785
Epoch 31/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 30.7520 - val_loss: 54.2059
Epoch 32/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 31.5812 - val_loss: 50.7807
Epoch 33/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 30.9731 - val_loss: 51.0038
Epoch 34/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 37.5553 - val_loss: 57.3778
Epoch 35/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 29.9348 - val_loss: 51.7766
Epoch 36/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 30.8427 - val_loss: 47.2875
Epoch 37/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 29.7144 - val_loss: 42.5311
Epoch 38/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 29.4085 - val_loss: 41.7530
Epoch 39/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 30.6910 - val_loss: 46.5274
Epoch 40/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 28.8517 - val_loss: 36.7256
Epoch 41/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 32.7138 - val_loss: 44.1281
Epoch 42/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 27.4585 - val_loss: 44.0610
Epoch 43/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 28.0715 - val_loss: 39.6533
Epoch 44/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 27.9242 - val_loss: 41.4529
Epoch 45/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 28.0402 - val_loss: 36.3717
Epoch 46/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 26.7646 - val_loss: 32.7501
Epoch 47/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 26.5061 - val_loss: 37.3841
Epoch 48/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 26.5658 - val_loss: 33.6442
Epoch 49/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 25.7154 - val_loss: 33.8221
Epoch 50/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 25.7792 - val_loss: 33.3046
Epoch 51/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 25.2924 - val_loss: 37.3515
Epoch 52/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 25.0997 - val_loss: 28.7751
Epoch 53/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 26.7918 - val_loss: 28.1812
Epoch 54/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 31.0724 - val_loss: 35.9274
Epoch 55/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 24.9493 - val_loss: 27.4769
Epoch 56/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 25.7476 - val_loss: 32.7605
Epoch 57/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 26.5288 - val_loss: 24.8952
Epoch 58/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 25.2022 - val_loss: 27.6862
Epoch 59/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 25.1210 - val_loss: 30.9566
Epoch 60/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 23.8437 - val_loss: 27.6629
Epoch 61/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 25.9136 - val_loss: 27.7006
Epoch 62/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 23.9086 - val_loss: 28.5958
Epoch 63/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 23.8424 - val_loss: 31.1557
Epoch 64/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 24.0038 - val_loss: 32.3311
Epoch 65/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 25.7081 - val_loss: 24.5915
Epoch 66/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 24.9817 - val_loss: 32.9587
Epoch 67/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 24.1625 - val_loss: 23.4953
Epoch 68/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 24.1233 - val_loss: 28.0079
Epoch 69/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 23.9709 - val_loss: 29.2668
Epoch 70/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 26.3785 - val_loss: 22.7940
Epoch 71/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 25.9539 - val_loss: 32.7150
Epoch 72/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 24.6896 - val_loss: 22.2979
Epoch 73/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 23.3989 - val_loss: 25.4279
Epoch 74/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 24.2139 - val_loss: 30.6143
Epoch 75/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 24.3550 - val_loss: 28.5847
Epoch 76/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 23.0597 - val_loss: 26.3187
Epoch 77/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 24.3109 - val_loss: 21.4632
Epoch 78/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 23.6789 - val_loss: 36.6810
Epoch 79/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 24.1985 - val_loss: 25.7189
Epoch 80/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 23.9402 - val_loss: 24.5654
Epoch 81/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 26.9761 - val_loss: 21.2724
Epoch 82/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 22.1591 - val_loss: 32.0224
Epoch 83/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 23.9142 - val_loss: 26.3596
Epoch 84/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 22.6838 - val_loss: 22.7591
Epoch 85/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 24.2325 - val_loss: 21.5815
Epoch 86/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 22.3876 - val_loss: 23.5807
Epoch 87/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 22.8414 - val_loss: 27.8624
Epoch 88/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 22.1227 - val_loss: 21.6943
Epoch 89/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 23.1296 - val_loss: 22.0925
Epoch 90/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 22.1578 - val_loss: 25.2153
Epoch 91/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 22.4606 - val_loss: 25.6900
Epoch 92/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 22.3219 - val_loss: 19.6922
Epoch 93/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 22.6280 - val_loss: 27.1547
Epoch 94/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 24.3456 - val_loss: 22.7976
Epoch 95/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 22.5895 - val_loss: 31.0175
Epoch 96/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 21.4230 - val_loss: 23.8902
Epoch 97/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 21.2976 - val_loss: 36.2731
Epoch 98/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 26.3363 - val_loss: 22.7141
Epoch 99/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 22.8948 - val_loss: 20.9656
Epoch 100/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 21.7588 - val_loss: 23.5864
Epoch 101/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 22.1924 - val_loss: 24.0040
Epoch 102/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 22.6387 - val_loss: 23.2375
Epoch 103/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 22.5450 - val_loss: 28.7793
Epoch 104/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 26.3430 - val_loss: 23.5397
Epoch 105/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 21.1857 - val_loss: 26.7936
Epoch 106/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 21.5817 - val_loss: 22.9313
Epoch 107/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 21.0343 - val_loss: 32.3385
Epoch 108/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 21.8313 - val_loss: 31.2270
Epoch 109/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 21.3396 - val_loss: 21.6334
Epoch 110/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 22.3428 - val_loss: 28.0369
Epoch 111/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 21.2794 - val_loss: 26.7747
Epoch 112/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 23.8673 - val_loss: 20.8209
Epoch 113/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 20.9104 - val_loss: 25.5447
Epoch 114/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 21.1451 - val_loss: 30.4209
Epoch 115/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 22.8360 - val_loss: 34.4521
Epoch 116/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 25.5016 - val_loss: 22.7296
Epoch 117/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 22.5922 - val_loss: 23.4978
Epoch 118/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 23.1819 - val_loss: 27.9891
Epoch 119/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 20.0008 - val_loss: 38.5114
Epoch 120/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 24.3754 - val_loss: 22.9167
Epoch 121/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 23.2391 - val_loss: 25.0633
Epoch 122/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 23.7426 - val_loss: 26.4178
Epoch 123/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 21.5488 - val_loss: 25.2706
Epoch 124/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 20.8672 - val_loss: 25.8705
Epoch 125/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 20.6643 - val_loss: 24.3045
Epoch 126/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 25.1688 - val_loss: 26.9754
Epoch 127/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 23.1361 - val_loss: 24.7157
Epoch 128/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 22.6171 - val_loss: 33.4728
Epoch 129/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 22.0215 - val_loss: 22.8135
Epoch 130/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 20.9915 - val_loss: 25.0549
Epoch 131/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 21.0111 - val_loss: 27.8192
Epoch 132/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 20.7244 - val_loss: 26.3896
Epoch 133/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 20.9634 - val_loss: 22.5660
Epoch 134/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 21.8342 - val_loss: 25.2270
Epoch 135/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 21.8673 - val_loss: 29.5178
Epoch 136/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 21.0563 - val_loss: 28.5034
Epoch 137/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 21.1615 - val_loss: 33.6349
Epoch 138/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 23.2890 - val_loss: 22.5086
Epoch 139/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 20.5948 - val_loss: 29.9772
Epoch 140/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 20.5295 - val_loss: 22.2388
Epoch 141/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 20.9187 - val_loss: 32.4371
Epoch 142/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 21.5403 - val_loss: 27.6764
Epoch 143/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 20.5641 - val_loss: 27.6136
Epoch 144/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 20.8271 - val_loss: 23.0318
Epoch 145/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 21.6530 - val_loss: 22.6814
Epoch 146/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 20.6528 - val_loss: 28.4764
Epoch 147/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 21.3760 - val_loss: 24.6513
Epoch 148/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 21.5319 - val_loss: 23.9373
Epoch 149/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 21.2633 - val_loss: 24.1645
Epoch 150/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 20.6069 - val_loss: 30.6993
Epoch 151/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 20.8831 - val_loss: 28.1425
Epoch 152/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 21.0412 - val_loss: 29.2268
Epoch 153/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 23.5416 - val_loss: 29.3726
Epoch 154/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 21.3655 - val_loss: 22.5982
Epoch 155/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 21.6084 - val_loss: 28.4214
Epoch 156/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 21.9127 - val_loss: 22.7637
Epoch 157/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 21.3548 - val_loss: 23.6672
Epoch 158/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 20.6398 - val_loss: 24.1406
Epoch 159/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 19.9755 - val_loss: 29.8123
Epoch 160/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 20.6498 - val_loss: 30.5003
Epoch 161/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 20.8590 - val_loss: 29.9000
Epoch 162/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 22.2310 - val_loss: 24.9602
Epoch 163/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 20.4501 - val_loss: 28.4021
Epoch 164/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 20.7527 - val_loss: 23.8697
Epoch 165/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 22.1362 - val_loss: 33.5301
Epoch 166/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 20.7553 - val_loss: 27.0726
Epoch 167/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 21.3210 - val_loss: 25.5051
Epoch 168/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 21.1254 - val_loss: 22.5558
Epoch 169/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 22.4623 - val_loss: 22.7486
Epoch 170/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 24.5941 - val_loss: 33.9761
Epoch 171/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 21.2936 - val_loss: 24.9454
Epoch 172/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 19.7961 - val_loss: 22.1190
Epoch 173/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 22.1625 - val_loss: 23.5767
Epoch 174/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 21.3930 - val_loss: 33.7495
Epoch 175/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 22.1446 - val_loss: 25.9572
Epoch 176/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 21.5637 - val_loss: 31.7492
Epoch 177/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 23.1485 - val_loss: 31.3418
Epoch 178/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 21.3698 - val_loss: 24.3036
Epoch 179/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 19.5060 - val_loss: 27.4460
Epoch 180/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 22.5472 - val_loss: 28.0890
Epoch 181/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 20.6684 - val_loss: 32.3162
Epoch 182/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 21.2515 - val_loss: 26.8595
Epoch 183/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 19.8338 - val_loss: 29.9604
Epoch 184/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 25.0263 - val_loss: 22.5336
Epoch 185/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 22.1728 - val_loss: 33.4285
Epoch 186/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 20.6426 - val_loss: 23.2923
Epoch 187/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 21.0603 - val_loss: 23.5770
Epoch 188/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 21.2602 - val_loss: 23.3218
Epoch 189/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 20.6075 - val_loss: 24.4692
Epoch 190/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 19.7269 - val_loss: 25.2643
Epoch 191/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 19.5392 - val_loss: 29.2755
Epoch 192/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 20.3673 - val_loss: 31.3857
Epoch 193/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 23.8873 - val_loss: 22.6727
Epoch 194/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 21.9123 - val_loss: 22.2682
Epoch 195/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 21.6478 - val_loss: 30.2012
Epoch 196/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 22.9039 - val_loss: 23.8891
Epoch 197/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 20.0876 - val_loss: 30.0955
Epoch 198/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 20.0550 - val_loss: 26.1313
Epoch 199/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 21.2401 - val_loss: 34.2249
Epoch 200/200
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 19.5996 - val_loss: 22.3226